################################################################################
configs:
  nginx.conf-angular:
    file: /run/configs/circabc-oss/angular/etc/nginx/nginx.conf-angular
  nginx.conf-proxy:
    file: /run/configs/circabc-oss/proxy/etc/nginx/nginx.conf-proxy
secrets:
  default.conf-angular:
    file: /run/secrets/circabc-oss/angular/etc/nginx/conf.d/default.conf-angular
  default.conf-proxy:
    file: /run/secrets/circabc-oss/proxy/etc/nginx/conf.d/default.conf-proxy
  password-root-db:
    file: /run/secrets/circabc-oss/db/password-root-db
  setup-db:
    file: /run/secrets/circabc-oss/db/init/setup-db
services:
  angular:
    configs:
    - mode: 0400
      source: nginx.conf-angular
      target: /etc/nginx/nginx.conf
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1  
    expose:
    - 8080
    image: academiaonline/circabc-oss:1.5-angular
    secrets:
    - mode: 0400
      source: default.conf-angular
      target: /etc/nginx/conf.d/default.conf
    volumes:
    - angular-nginx-cache:/var/cache/nginx
    - angular-nginx-run:/var/run
  db:
    command:
    - --lower-case-table-names=1
    - --transaction-isolation=READ-COMMITTED
    - --datadir=/var/lib/mysql/data
    - --explicit-defaults-for-timestamp=1
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_bin
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    environment:
    - MYSQL_ROOT_PASSWORD_FILE=/etc/mysql/password-root-db
    expose:
    - 3306
    image: mysql:5.6.51@sha256:19fc1ff0d34a3373628f57137f700da9b8d703b51defecaa6f1e8127565868c5
    secrets:
    - mode: 0400
      source: password-root-db
      target: /etc/mysql/password-root-db
    - mode: 0444
      source: setup-db
      target: /docker-entrypoint-initdb.d/setup.sql
    volumes:
    - db-mysql:/var/lib/mysql
  proxy:
    configs:
    - mode: 0400
      source: nginx.conf-proxy
      target: /etc/nginx/nginx.conf  
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
    expose:
    - 8080
    image: academiaonline/nginx:8.3
    ports:
    - 8080:8080
    secrets:
    - mode: 0400
      source: default.conf-proxy
      target: /etc/nginx/conf.d/default.conf
    volumes:
    - proxy-nginx-cache:/var/cache/nginx
    - proxy-nginx-run:/var/run
  tomcat:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    expose:
    - 8080
    image: academiaonline/circabc-oss:1.5-tomcat
    volumes:
    - tomcat-local:/usr/local/tomcat/circabc_local
    - tomcat-shared:/usr/local/tomcat/circabc_shared
version: "3.8"
volumes:
  db-mysql:
  angular-nginx-cache:
  angular-nginx-run:
  proxy-nginx-cache:
  proxy-nginx-run:
  tomcat-local:
  tomcat-shared:
################################################################################
