################################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
configs:
  nginx.conf:
    file: /run/configs/proxy/nginx/nginx.conf
#    external: true
secrets:
  default.conf:
    file: /run/secrets/proxy/nginx/conf.d/default.conf
#    external: true
  mysql-root-password:
    file: /run/secrets/db/mysql-root-password
  setup.sql:
    file: /run/secrets/db/mysql/init/setup.sql
#    external: true
services:
  angular:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1  
    expose:
    - 80
    image: academiaonline/circabc-oss:latest-angular
  db:
    command: --lower_case_table_names=1 --transaction-isolation=READ-COMMITTED
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1    
    environment:
    - MYSQL_ROOT_PASSWORD_FILE=/etc/mysql/mysql-root-password
    expose:
    - 3306
    image: mysql:5.6
    secrets:
    - mode: 0400
      source: mysql-root-password
      target: /etc/mysql/mysql-root-password
    - mode: 0444
      source: setup.sql
      target: /docker-entrypoint-initdb.d/setup.sql
    volumes:
    - db:/var/lib/mysql
  proxy:
    configs:
    - mode: 0400
      source: nginx.conf
      target: /etc/nginx/nginx.conf  
    deploy:
#      mode: global
      placement:
        constraints:
        - node.role == worker
    expose:
    - 80
    image: academiaonline/nginx:8.2
    ports:
    - 30000:80
    secrets:
    - mode: 0400
      source: default.conf
      target: /etc/nginx/conf.d/default.conf    
    volumes:
    - nginx-cache:/var/cache/nginx
    - nginx-run:/var/run
  tomcat:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1  
    expose:
    - 8080
    image: academiaonline/circabc-oss:latest-tomcat
version: "3.8"
volumes:
  db:
  nginx-cache:
  nginx-run:
      
