################################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
configs:
  nginx.conf.angular:
    file: /run/configs/angular/nginx/nginx.conf.angular
  nginx.conf.proxy:
    file: /run/configs/proxy/nginx/nginx.conf.proxy
secrets:
  default.conf.angular:
    file: /run/secrets/angular/nginx/conf.d/default.conf.angular
  default.conf.proxy:
    file: /run/secrets/proxy/nginx/conf.d/default.conf.proxy
  mysql-root-password:
    file: /run/secrets/db/mysql-root-password
  setup.sql:
    file: /run/secrets/db/mysql/init/setup.sql
services:
  angular:
    configs:
    - mode: 0400
      source: nginx.conf.angular
      target: /etc/nginx/nginx.conf
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1  
    expose:
    - 8080
    image: academiaonline/circabc-oss:test-angular
    secrets:
    - mode: 0400
      source: default.conf.angular
      target: /etc/nginx/conf.d/default.conf
    volumes:
    - angular-nginx-cache:/var/cache/nginx
    - angular-nginx-run:/var/run
  db:
    command:
    - --lower-case-table-names=1
    - --transaction-isolation=READ-COMMITTED
    - --datadir=/var/lib/mysql/data
    - --explicit-defaults-for-timestamp=1
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_bin
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
    env_file:
    - /run/configs/db/db.env
    environment:
    - MYSQL_ROOT_PASSWORD_FILE=/etc/mysql/mysql-root-password
    expose:
    - 3306
    image: mysql:5.6
    secrets:
    - mode: 0400
      source: mysql-root-password
      target: /etc/mysql/mysql-root-password
    - mode: 0444
      source: setup.sql
      target: /docker-entrypoint-initdb.d/setup.sql
    volumes:
    - db:/var/lib/mysql
  proxy:
    configs:
    - mode: 0400
      source: nginx.conf.proxy
      target: /etc/nginx/nginx.conf  
    deploy:
#      mode: global
      placement:
        constraints:
        - node.role == worker
    expose:
    - 8080
    image: academiaonline/nginx:8.3
    ports:
    - 30000:8080
    secrets:
    - mode: 0400
      source: default.conf.proxy
      target: /etc/nginx/conf.d/default.conf
    volumes:
    - proxy-nginx-cache:/var/cache/nginx
    - proxy-nginx-run:/var/run
  tomcat:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1  
    expose:
    - 8080
    image: academiaonline/circabc-oss:test-tomcat
    volumes:
    - tomcat-local:/usr/local/tomcat/circabc_local
    - tomcat-shared:/usr/local/tomcat/circabc_shared
version: "3.8"
volumes:
  db:
  angular-nginx-cache:
  angular-nginx-run:
  proxy-nginx-cache:
  proxy-nginx-run:
  tomcat-local:
  tomcat-shared:
      
