services:
  angular:
    expose:
    - 80
    image: academiaonline/circabc-oss:latest-angular
  db:
    command: --lower_case_table_names=1 --transaction-isolation=READ-COMMITTED
    environment:
    - MYSQL_ROOT_PASSWORD=password
    expose:
    - 3306
    image: mysql:5.6
    volumes:
    - ${PWD}/circabc-docker/mysql/init:/docker-entrypoint-initdb.d/:ro
  db_admin:
    environment: 
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    expose:
    - 80
    image: phpmyadmin/phpmyadmin
  proxy: 
    expose:
    - 80
    - 443
    image: nginx:alpine
    ports:
    - 8080:80
    - 8443:443
    volumes:
    - ${PWD}/circabc-docker/proxy/conf:/etc/nginx
  tomcat:
    expose:
    - 8080
    image: academiaonline/circabc-oss:latest-tomcat
version: "3.8"
      
