################################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
name: CI                                                                       #
on:                                                                            #
  push:                                                                        #
    branches:                                                                  #
    - v0.2                                                                     #
jobs:                                                                          #
  docker:                                                                      #
    runs-on: ubuntu-18.04                                                      #
    steps:                                                                     #
    - name: checkout                                                           #
      uses: actions/checkout@v2                                                #
    - name: test                                                               #
      run: |                                                                   #
        set -x                                                                 ;
        ########################################################################
        function _docker_run {                                                 \
          docker run                                                           \
            -d                                                                 \
            ${environment}                                                     \
            --name ${name}                                                     \
            --network ${network}                                               \
            ${ports}                                                           \
            ${volumes}                                                         \
            ${image}                                                           \
            ${command}                                                         \
                                                                               ;
        }                                                                      ;
        ########################################################################
        branch=$( basename ${GITHUB_REF} )                                     ;
        project=$( basename ${GITHUB_REPOSITORY} | tr A-Z a-z )                ;
        repository=$( echo ${GITHUB_REPOSITORY} | tr A-Z a-z )                 ;
        ########################################################################
        dir=circabc-docker                                                     ;
        ########################################################################
        echo $branch | grep ^v[0-9]                                            \
          && release=$( echo $branch | awk -F^v '{ print $2 }' )               \
          || release=latest                                                    ;
        ########################################################################
        for app in angular tomcat                                              ;
          do                                                                   \
            docker build                                                       \
              --file Dockerfile.${app}                                         \
              --tag ${repository}:${release}-testing-${app}                    \
              ${PWD}                                                           \
                                                                               ;
          done                                                                 ;
        ########################################################################
        for app in angular db db_admin proxy tomcat                            ;
          do                                                                   \
            docker network create $app                                         ;
          done                                                                 ;
        ########################################################################
        command="                                                              \
          --lower_case_table_names=1 --transaction-isolation=READ-COMMITTED    \
        "                                                                      ;
        environment="                                                          \
          -e MYSQL_ROOT_PASSWORD=password                                      \
        "                                                                      ;
        name=db                                                                ;
        network=db                                                             ;
        ports="                                                                \
          -p 3306:3306                                                         \
        "                                                                      ;
        volumes="                                                              \
          -v ${PWD}/circabc-docker/mysql/init:/docker-entrypoint-initdb.d/:ro  \
        "                                                                      ;
        ########################################################################
        image=mysql:5.6                                                        ;
        ########################################################################
        _docker_run                                                            ;
        ########################################################################
        command="                                                              \
        "                                                                      ;
        environment="                                                          \
          -e PMA_ARBITRARY=1                                                   \
          -e PMA_HOST=db                                                       \
          -e PMA_PORT=3306                                                     \
        "                                                                      ;
        name=db_admin                                                          ;
        network=db_admin                                                       ;
        ports="                                                                \
          -p 83:80                                                             \
        "                                                                      ;
        volumes="                                                              \
        "                                                                      ;
        ########################################################################
        image=phpmyadmin/phpmyadmin                                            ;
        ########################################################################
        _docker_run                                                            ;
        ########################################################################
        command="                                                              \
        "                                                                      ;
        environment="                                                          \
        "                                                                      ;
        name=tomcat                                                            ;
        network=tomcat                                                         ;
        ports="                                                                \
          -p 81:8080                                                           \
        "                                                                      ;
        volumes="                                                              \
        "                                                                      ;
        ########################################################################
        image=${repository}:${release}-testing-${name}                         ;
        ########################################################################
        _docker_run                                                            ;
        ########################################################################
        command="                                                              \
        "                                                                      ;
        environment="                                                          \
        "                                                                      ;
        name=angular                                                           ;
        network=angular                                                        ;
        ports="                                                                \
          -p 82:80                                                             \
        "                                                                      ;
        volumes="                                                              \
        "                                                                      ;
        ########################################################################
        image=${repository}:${release}-testing-${name}                         ;
        ########################################################################
        _docker_run                                                            ;
        ########################################################################
        command="                                                              \
        "                                                                      ;
        environment="                                                          \
        "                                                                      ;
        name=proxy                                                             ;
        network=proxy                                                          ;
        ports="                                                                \
          -p 8080:80                                                           \
          -p 8443:443                                                          \
        "                                                                      ;
        volumes="                                                              \
          -v ${PWD}/circabc-docker/proxy/conf:/etc/nginx                       \
        "                                                                      ;
        ########################################################################
        image=nginx:alpine                                                     ;
        ########################################################################
        _docker_run                                                            ;
        ########################################################################
        for app in angular db db_admin proxy tomcat                            ;
          do                                                                   \
            docker logs $app
          done                                                                 ;
################################################################################
